LOAD DATA
INFILE libro_fixo.txt
INTO TABLE librosplaneta
APPEND
WHEN (EDITORIAL='planeta')
TRAILING NULLCOLS
(
CLIBRO POSITION(1:6),
TITULO POSITION(7:36),
EDITORIAL FILLER POSITION(37:56),
DEDICION POSITION(57:64) "TO_DATE(:DEDICION,'YYYYMMDD')", 
CODAUTOR POSITION(67:69) 
)
